import i18n from 'i18next';

const strings = {
    oTPVerification: () => i18n.t('screens.loginScreen.text.oTPVerification'),
    sentMobileNumber: () => i18n.t('screens.loginScreen.text.sentMobileNumber'),
    number: () => i18n.t('screens.loginScreen.text.number'),
    verifyOTP: () => i18n.t('screens.loginScreen.text.verifyOTP'),
    didNotReceive: () => i18n.t('screens.loginScreen.text.didNotReceive'),
    successfully: () => i18n.t('screens.loginScreen.text.successfully'),
    successfullyVerified: () => i18n.t('screens.loginScreen.text.successfullyVerified'),
    selectLanguage: () => i18n.t('screens.loginScreen.text.selectLanguage'),
    close: () => i18n.t('screens.loginScreen.text.close'),
    next: () => i18n.t('screens.loginScreen.text.next'),
    skip: () => i18n.t('screens.loginScreen.text.skip'),
    finish: () => i18n.t('screens.loginScreen.text.finish'),
    placeholderPhone: () => i18n.t('screens.loginScreen.text.placeholderPhone'),
    buttonSignUp: () => i18n.t('screens.loginScreen.text.buttonSignUp'),
    dontHaveAnAccount: () => i18n.t('screens.loginScreen.text.dontHaveAnAccount'),
    placeholderFirstName: () => i18n.t('screens.loginScreen.text.placeholderFirstName'),
    placeholderLastName: () => i18n.t('screens.loginScreen.text.placeholderLastName'),
    placeholderDateOfBirth: () => i18n.t('screens.loginScreen.text.placeholderDateOfBirth'),
    placeholderEmail: () => i18n.t('screens.loginScreen.text.placeholderEmail'),
    placeholderPassword: () => i18n.t('screens.loginScreen.text.placeholderPassword'),
    confirmPassword: () => i18n.t('screens.loginScreen.text.confirmPassword'),
    forgotPassword: () => i18n.t('screens.loginScreen.text.forgotPassword'),
    policyText: () => i18n.t('screens.loginScreen.text.policyText'),
    buttonLogin: () => i18n.t('screens.loginScreen.text.buttonLogin'),
    buttonResend: () => i18n.t('screens.loginScreen.text.buttonResend'),
    alreadyHaveAccount: () => i18n.t('screens.loginScreen.text.alreadyHaveAccount'),
    continue: () => i18n.t('screens.loginScreen.text.continue'),
    SignIn: () => i18n.t('screens.loginScreen.text.SignIn'),
    Welcome: () => i18n.t('screens.loginScreen.text.Welcome'),
    ContinuePhoneNumber: () => i18n.t('screens.loginScreen.text.ContinuePhoneNumber'),
    ContinueGoogle: () => i18n.t('screens.loginScreen.text.ContinueGoogle'),
    ContinueFacebook: () => i18n.t('screens.loginScreen.text.ContinueFacebook'),
    ContinueApple: () => i18n.t('screens.loginScreen.text.ContinueApple'),
    NoWorries: () => i18n.t('screens.loginScreen.text.NoWorries'),
    HomeScreen: () => i18n.t('screens.loginScreen.text.HomeScreen'),
    AddPayment: () => i18n.t('screens.loginScreen.text.AddPayment'),
    Settings: () => i18n.t('screens.loginScreen.text.Settings'),
    Language: () => i18n.t('screens.loginScreen.text.Language'),
    Appearance: () => i18n.t('screens.loginScreen.text.Appearance'),
    Logout: () => i18n.t('screens.loginScreen.text.Logout'),
    AddShipment: () => i18n.t('screens.loginScreen.text.AddShipment'),
};

export default strings;